Inmob_Venta/Inmob_Venta/urls.py
from django.conf                import settings
from django.conf.urls.static    import static 
from django.contrib             import admin
from django.contrib.auth        import views as auth_views
from django.urls                import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.inicio, name = "inicio"),#Vista basado en funcion
    path('', views.Inicio.as_view(), name = "inicio"),

    path('login/',auth_views.LoginView.as_view(template_name="login.html"), name= "login"),
    path('logout/',auth_views.logout_then_login, name="logout"),

    #Includes
    path("Producto/",include('apps.productos.urls')),
    path("Usuario/",include('apps.usuarios.urls'))
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Inmob_Venta/apps/usuarios/urls.py
from django.urls         import path
from .                   import views

app_name = "usuario"

urlpatterns = [
    path('Registrarme/', views.Registrarme.as_view(), name = "registrarme"),
    path('Listado/', views.ListarUser.as_view(), name = "listar"),
    path('Eliminar/<int:pk>/',views.BorrarUser.as_view(), name = "elimina"),
    path("Editar/<int:pk>/", views.EditarUser.as_view(), name = "editar"),
    path("Mi_Usuario/", views.MiUser.as_view(), name = "mi_usuario"),
    path("Mi_Usuario/Editar_Mi_Usuario/<int:pk>/", views.EditarMiUser.as_view(), name = "editar_miuser"),
    

  

]

Inmob_Venta/apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class Usuario (AbstractUser):
    dni = models.IntegerField(null=True , blank=True)
    #foto = models.ImageField(upload_to="usuarios", default= False)
    es_administrador = models.BooleanField(default=False) 

    class Meta:
        db_table:"usuarios"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

Inmob_Venta/apps/usuarios/forms.py
from django 					import forms
from django.core.exceptions		import ValidationError
from django.contrib.auth.forms 	import UserCreationForm
from django.forms 				import ModelForm
from . models import Usuario

class UsuarioForm(UserCreationForm):
	
	username = forms.CharField(label="Usurario",widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Ingrese su nombre de usuario"}))
	first_name = forms.CharField(label="Nombre",widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Ingrese su nombre "}))
	last_name = forms.CharField(label="Apellido",widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Ingrese su Apellido "}))
	email = forms.CharField(label="Email",widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Ingrese su email "}))
	dni = forms.CharField(label="DNI",widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Ingrese su DNI "}))

	#password = forms.CharField(widget=forms.PasswordInput())
	

	class Meta:
		model = Usuario
		fields = ["username", "first_name","last_name","email" , "dni"]
	"""
		#validadciones 
	def clean_username(self):
		username = self.cleaned_data["username"]

		if  "12" not in username :
			raise ValidationError(" El nombre de usuario de incluir un numero 12")
		return username
	"""
class UsuarioEdit(ModelForm):
	
	username = forms.CharField(label="Usurario",widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Ingrese su nombre de usuario"}))
	first_name = forms.CharField(label="Nombre",widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Ingrese su nombre "}))
	last_name = forms.CharField(label="Apellido",widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Ingrese su Apellido "}))
	email = forms.CharField(label="Email",widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Ingrese su email "}))
	dni = forms.CharField(label="DNI",widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Ingrese su DNI "}))
	

	class Meta:
		model = Usuario
		fields = ["username", "first_name","last_name","email" , "dni"]

Inmob_Venta/apps/usuarios/views.py
from django.shortcuts           	import render
from django.urls 					import reverse_lazy
from django.views.generic 			import ListView, CreateView
from django.contrib.auth.mixins		import LoginRequiredMixin
from apps.core.mixins 				import AdminRequiredMixins
from django.views.generic.edit 		import UpdateView, DeleteView
from django.views.generic.detail 	import DetailView
from django.urls 					import reverse_lazy


from  .forms 					import UsuarioForm, UsuarioEdit
from  .models 					import Usuario


class Registrarme(CreateView):
	template_name= "usuarios/registrar.html"
	model = Usuario
	form_class = UsuarioForm

	def get_success_url(self, **kwargs):
		return reverse_lazy("login")

class ListarUser(AdminRequiredMixins,LoginRequiredMixin,ListView):
	template_name = "usuarios/listar_us.html"
	model = Usuario
	context_object_name= "usuarios"
	paginate_by=2


	def get_queryset(self):
		#self.request
		return Usuario.objects.all().order_by("id")


class BorrarUser(LoginRequiredMixin,AdminRequiredMixins,DeleteView):
	template_name= "usuarios/eliminar_us.html"
	model = Usuario
	form_class = UsuarioForm

	def get_success_url(self, **kwargs):
		return reverse_lazy("usuario:listar")

class EditarUser(LoginRequiredMixin,UpdateView):
	template_name= "usuarios/editar_us.html"
	model = Usuario
	form_class = UsuarioEdit
	
	def get_success_url(self, **kwargs):
		return reverse_lazy("usuario:listar")


class MiUser(LoginRequiredMixin,ListView):
	template_name = "usuarios/mi_us/mi_user.html"
	model = Usuario
	context_object_name= "usuarios"


	def get_queryset(self):
		self.request

class EditarMiUser(LoginRequiredMixin,UpdateView):
	template_name= "usuarios/mi_us/editar_mi_us.html"
	model = Usuario
	form_class = UsuarioEdit
	
	def get_success_url(self, **kwargs):
		return reverse_lazy("usuario:mi_usuario")
	

Inmob_Venta/templates/usuarios/editar_us.html
{% extends "base/base.html" %}
{% block portada %}
		<section class="py-5 text-center container">
		    <div class="row py-lg-5">
		      <div class="col-lg-6 col-md-8 mx-auto">
		      	{% include "include/alert.html" %}
		      	<div class="alert alert-primary d-flex align-items-center" role="alert">
					  <svg class="bi flex-shrink-0 me-2" width="30" height="30" role="img" aria-label="Info:">
					  	<use xlink:href="#info-fill"/>
					  </svg>
				  <div>
					   <h1 class="py-1 text-center container">Actualizacion de datos </h1>
			        	<h1 class="py-1 text-center container">{{object.first_name }} {{object.last_name}}  </h1>
				  </div>
				</div>
		      </div>
		    </div>
		</section>
	{% endblock portada %}
{% block contenido %}
			{% include "include/form_errors.html" %}
				<form method="POST">{% csrf_token %}
						{% include "include/forms.html" %}
					<div class="row" style="padding:10px;">
						<div class="col">
						<button type='submit' class="btn btn-outline-success">Guardar</button>
						<a class="btn btn-outline-danger" href="{% url 'usuario:listar' %}" >Cancelar</a>
					</div>
				</form>
{% endblock contenido %}

Inmob_Venta/templates/usuarios/eliminar_us.html
{% extends "base/base.html" %}
{% block Menu %}
{% endblock Menu %}
	{% block portada %}
		<section class="py-5 text-center container" >
		    <div class="row py-lg-5">
		      <div class="col-lg-6 col-md-8 mx-auto">
		      	{% include "include/alert.html" %}
		      	<div class="alert alert-warning d-flex align-items-center" role="alert">
					  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/>
					  </svg>  
				  <div>
				    <h1 class="fw-light">Usted esta por eliminar al usuario </h1>
		       		<h1>{{object.first_name }} {{object.last_name}}</h1>
				  </div>
				</div>
		      </div>
		    </div>
		</section>
	{% endblock portada %}
{% block contenido %}

		
	<form method="POST" enctype="multipart/form-data">{% csrf_token %}
		{% include "include/form_errors.html" %}


		{{form.as_p}}
	
		<table class="table table-success table-striped">
			{% include "base/menu.html" %}
		  <thead>
		    <tr>
		      <th scope="col">Id</th>
		      <th scope="col">Nombre</th>
		      <th scope="col">Usuario</th>
		      <th scope="col">dni</th>
		      <th scope="col">email</th>
		    </tr>
		  </thead>
		  <tbody>

		    	<tr>
			      <th scope="row">{{object.id}}</th>
			      <td>{{object.first_name }} {{object.last_name}}</td>
			      <td> {{object.username}}</td>
			      <td> {{object.dni}}</td>
			      <td> {{object.email}}</td>
			    </tr>
		  </tbody>
		</table>
		<div class="row" style="padding:10px;">
			<div class="col">
				<button type='submit' class="btn btn-outline-danger">Eliminar</button>
				<a class="btn btn-outline-primary" href="{% url 'usuario:listar' %}" >Cancelar</a>
			</div>
		</div>
	</form>
{% endblock contenido %}

Inmob_Venta/templates/usuarios/listar_us.html
{% extends "base/base.html" %}
	{% block Menu %}
		
	{% endblock Menu %}
	{% block footer %}
			
	{% endblock footer %}

	{% block portada %}
		<section class="py-5 text-center container">
		    <div class="row py-lg-5">
		      <div class="col-lg-6 col-md-8 mx-auto">
		        <h1 class="text-success">
		        	<div class="fst-italic">Listado de Usuarios</div>  
		        </h1>
		      </div>
		    </div>
		</section>
	{% endblock portada %}
{% block contenido %}

	
	<div class="row" style="padding:20px;">
		<div class="col">
			
			{% include "base/menu.html" %}
		</div>
	</div>
	 	
	<table class="table table-success table-striped">
		  <thead>
		    <tr>
		      <th scope="col">Id</th>
		      <th scope="col">Nombre</th>
		      <th scope="col">Usuario</th>
		      <th scope="col">dni</th>
		      <th scope="col">email</th>
		      <th scope="col">Acciones</th>
		    </tr>
		  </thead>
		  <tbody>
		    {% for u in usuarios  %}
		    	<tr>
			      <th scope="row">{{u.id}}</th>
			      <td>{{u.first_name}} {{u.last_name}}</td>
			      <td> {{u.username}}</td>
			      <td> {{u.dni}}</td>
			      <td> {{u.email}}</td>
			      <td>
			      	<a> </a>
			      	<a href="{% url 'usuario:editar' u.id %}"class="link-success">Editar</a>
			      	<a href="{% url 'usuario:elimina' u.id %}"class="link-danger">Eliminar</a>
			      </td>
			   	</tr> 
		    {% endfor %}
		  </tbody>
	</table>

	{% include "include/paginador.html" %}
{% endblock contenido %}

Inmob_Venta/templates/usuarios/registrar.html
{% extends "base/base.html" %}
	{% block Menu %}
		
	{% endblock Menu %}
	{% block footer %}
			
	{% endblock footer %}

	{% block portada %}
	<section class="py-5 text-center container">
	    <div class="row py-lg-5">
	      <div class="col-lg-6 col-md-8 mx-auto">
			  <div>
				   <h1 class="py-1 text-center container">Gracias por registrarce</h1>
		        	
			  </div>
			</div>
	      </div>
	    </div>
	</section>
	{% endblock portada %}
{% block contenido %}
	<div style="border: solid #084298;padding: 1.5rem;margin-right: 0;margin-left: 0;border-width: 1px;border-top-left-radius: 0.25rem;	    border-top-right-radius: 0.25rem;">

	
		<form method="POST">{% csrf_token %}
			{% include "include/form_errors.html" %}
			{{form.as_p}}
			<!--{{form.username.label}}-->
			<!--{{form.username}}-->
			<div class="row" style="padding:10px;">
				<div class="col" style="padding:30px;">
					<button type='submit' class="btn btn-outline-success">Registrarme</button>
					<a href="{% url 'inicio' %}" class="btn btn-outline-danger">Cancelar</a>
				</div>
			</div>
		</form>
	</div>
{% endblock contenido %}