Inmob_Venta/Inmob_Venta/urls.py
from django.conf                import settings
from django.conf.urls.static    import static 
from django.contrib             import admin
from django.contrib.auth        import views as auth_views
from django.urls                import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.inicio, name = "inicio"),#Vista basado en funcion
    path('', views.Inicio.as_view(), name = "inicio"),

    path('login/',auth_views.LoginView.as_view(template_name="login.html"), name= "login"),
    path('logout/',auth_views.logout_then_login, name="logout"),

    #Includes
    path("Producto/",include('apps.productos.urls')),
    path("Usuario/",include('apps.usuarios.urls'))
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Inmob_Venta/apps/productos/urls.py
from django.urls         import path
from .                   import views

app_name = "productos"

urlpatterns = [
    path('Detalle/<int:pk>/', views.Detalle.as_view(), name = "detalle"),
    
    #admini
    path("Admin/Listar/", views.ListarAdmin.as_view(), name="admin_listar"),
    path("Listar/", views.Listar.as_view(), name="listar"),
    path("Admin/Nuevo/", views.NuevoAdmin.as_view(), name = "admin_nuevo"),
    path("Admin/Editar/<int:pk>/", views.EditarAdmin.as_view(), name = "admin_editar"),
    path("Admin/Eliminar/<int:pk>/", views.EliminarAdmin.as_view(), name = "admin_eliminar"),

    path("Mis_productos/",views.MisProductos.as_view(), name="Mis_procductos"),
  

]

Inmob_Venta/apps/usuarios/urls.py
from django.urls         import path
from .                   import views

app_name = "usuario"

urlpatterns = [
    path('Registrarme/', views.Registrarme.as_view(), name = "registrarme"),
    path('Listado/', views.ListarUser.as_view(), name = "listar"),
    path('Eliminar/<int:pk>/',views.BorrarUser.as_view(), name = "elimina"),
    path("Editar/<int:pk>/", views.EditarUser.as_view(), name = "editar"),
    path("Mi_Usuario/", views.MiUser.as_view(), name = "mi_usuario"),
    path("Mi_Usuario/Editar_Mi_Usuario/<int:pk>/", views.EditarMiUser.as_view(), name = "editar_miuser"),
    

  

]

Inmob_Venta/templates/base/alerta.html
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
	  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
	    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
	  </symbol>
	  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
	    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
	  </symbol>
	  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
	    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
	  </symbol>
</svg>

Inmob_Venta/templates/base/base.html
<html lang="en">
	<head>
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="description" content="">
	    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
	    <meta name="generator" content="Hugo 0.88.1">
	    <title>Inomb Ventas</title>

	    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/album/">

	    

	    <!-- Bootstrap core CSS -->
		<!-- CSS only -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

	    <!-- Favicons -->
			<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
			<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
			<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
			<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
			<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
			<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
			<meta name="theme-color" content="#7952b3">


	    <style>
	      .bd-placeholder-img {
	        font-size: 1.125rem;
	        text-anchor: middle;
	        -webkit-user-select: none;
	        -moz-user-select: none;
	        user-select: none;
	      }

	      @media (min-width: 768px) {
	        .bd-placeholder-img-lg {
	          font-size: 3.5rem;
	        }
	      }
	    </style>

	</head>
  	<body>
    
		{% include "base/header.html" %}

		<main>
			{% block portada %}
				{% include "base/portada.html" %}
			{% endblock portada %}
		  

			<div class=" p-3 mb-2 bg-light">
				<div class="container">
					{% block Menu %}
						{% include "base/menu.html" %}
					{% endblock Menu %}

					{% block contenido %}
						
					{% endblock contenido %}
				</div>
			</div>

		</main>
			{% block footer %}
				{% include "base/footer.html" %}
			{% endblock footer %}
			


	    	<!-- JavaScript Bundle with Popper -->
			<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

	      
	 
	</body>
	
</html>

Inmob_Venta/templates/base/footer.html
<footer class="text-bg-info py-5">
	  <div class="container">
	    <p class="float-end mb-1">
	      <!--<a href="{% url 'inicio'  %}">Ir al inicio</a>-->
	    </p>
	    <h3 class="mb-1">Sitio destinado a la compra/venta de inmubles </h3>	    	
	    <a class="float-end mb-1" href="#">Subir</a>
	    <!--
	    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.1/getting-started/introduction/">getting started guide</a>.</p>-->
	  </div>
</footer>

Inmob_Venta/templates/base/header.html
<header>
		  <div class="collapse bg-dark" id="navbarHeader">
		    <div class="container">
		      <div class="row">
		        <div class="col-sm-8 col-md-7 py-4">
		          <h4 class="text-white">Sobre nostros</h4>
		          <p class="text-muted">Sitio dedicado a la compra y venta de inmuebles </p>
		        </div>
		        <div class="col-sm-4 offset-md-1 py-4">
		          <h4 class="text-white">Opciones </h4>
		          <ul class="list-unstyled">
		          	{% if user.is_authenticated %}
						<li><a href="{% url 'logout' %}" class="text-white">Cerrar sesion</a></li>
					{% else %}
						<li><a href="{% url 'login' %}" >Iniciar sesion</a></li>
						<li> <a href="{% url 'usuario:registrarme' %}">Registrarse</a></li>
					{% endif %}
		            <!--
		            <li><a href="#" class="text-white">Follow on Twitter</a></li>
		            <li><a href="#" class="text-white">Like on Facebook</a></li>
		            <li><a href="#" class="text-white">Email me</a></li>
		        	-->
		          </ul>
		        </div>
		      </div>
		    </div>
		  </div>
		  <div class="navbar navbar-dark bg-dark shadow-sm">
		    <div class="container">
		      <a href=" {% url 'inicio'  %} " class="navbar-brand d-flex align-items-center">
		        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
		        <strong>Inmob Ventas</strong>
		      </a>
		      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
		        <span class="navbar-toggler-icon"></span>
		      </button>
		    </div>
		  </div>
</header>

Inmob_Venta/templates/base/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-ligth">

	  <div class="container-fluid">
		    <a class="btn btn-dark" >Menu</a>    
	    <div class="collapse navbar-collapse" id="navbarNav">
		      <ul class="navbar-nav">
			        
			        {% if user.is_authenticated %}
			        	{% if user.es_administrador %}
			        		<li class="nav-item">
					          	<a class="btn btn-outline-secondary" aria-current="page" href="{% url 'inicio'  %}">Inicio</a>
					        </li>  
					        <li class="nav-item">
								<a class="btn btn-outline-secondary" href="{% url 'productos:admin_listar' %}">Catalogo</a>
							</li>
							<li class="nav-item">
								<a class="btn btn-outline-secondary" href="{% url 'productos:Mis_procductos' %}">Mis productos</a>
							</li>
							<li class="nav-item">
								<a class="btn btn-outline-secondary" href="{% url 'usuario:listar' %}">Lista de Usuarios</a>
							</li>
						{% else %}
							<li class="nav-item">
					          	<a class="btn btn-outline-secondary" aria-current="page" href="{% url 'inicio'  %}">Inicio</a>
					        </li>
					        <li class="nav-item">
								<a class="btn btn-outline-secondary" href="{% url 'productos:listar' %}">Catalogo</a>
							</li>
							<li class="nav-item">
								<a class="btn btn-outline-secondary" href="{% url 'usuario:mi_usuario' %}">Mi usuario</a>
							</li>
						{% endif %}
			        {% endif %}
		        	<!--
			        <li class="nav-item">
			          <a class="nav-link disabled">Disabled</a>
			        </li>
			    	-->
		      </ul>
	    </div>
	  </div>
</nav>

Inmob_Venta/templates/base/portada.html
{% if user.is_authenticated %}

	<section class="py-5 text-center container">

			    <div class="row py-lg-5">
			      <div class="col-lg-6 col-md-8 mx-auto">
			        <h1  class="text-success"> 
			        	<div class="fst-italic">Hola</div> 
			        </h1>
			        <h1  class="text-success ">
				        <div class="fst-italic">
				        	{{user.first_name}} {{user.last_name}}
				        </div>
			    	</h1>
			      </div>
			    </div>
			    
	</section>
{% else %}
	<section class="py-5 text-center container">
			    <div class="row py-lg-5">
			      <div class="col-lg-6 col-md-8 mx-auto">
			        <h1 class="fw-light">Bienvenidos al sitio de Compra </h1>
			        <p class="lead text-muted">Encontra la propiedad que tanto estabas buscando </p>
			        <p class="lead text-muted">Para acceder a mas informacion registrarce</p>
			        <!--
			        <p>
			          <a href="#" class="btn btn-primary my-2">Main call to action</a>
			          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
			        </p>
			    	-->
			      </div>
			    </div>
			    
	</section>
{% endif %}