Inmob_Venta/Inmob_Venta/urls.py
from django.conf                import settings
from django.conf.urls.static    import static 
from django.contrib             import admin
from django.contrib.auth        import views as auth_views
from django.urls                import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.inicio, name = "inicio"),#Vista basado en funcion
    path('', views.Inicio.as_view(), name = "inicio"),

    path('login/',auth_views.LoginView.as_view(template_name="login.html"), name= "login"),
    path('logout/',auth_views.logout_then_login, name="logout"),

    #Includes
    path("Producto/",include('apps.productos.urls')),
    path("Usuario/",include('apps.usuarios.urls'))
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Inmob_Venta/apps/productos/urls.py
from django.urls         import path
from .                   import views

app_name = "productos"

urlpatterns = [
    path('Detalle/<int:pk>/', views.Detalle.as_view(), name = "detalle"),
    
    #admini
    path("Admin/Listar/", views.ListarAdmin.as_view(), name="admin_listar"),
    path("Listar/", views.Listar.as_view(), name="listar"),
    path("Admin/Nuevo/", views.NuevoAdmin.as_view(), name = "admin_nuevo"),
    path("Admin/Editar/<int:pk>/", views.EditarAdmin.as_view(), name = "admin_editar"),
    path("Admin/Eliminar/<int:pk>/", views.EliminarAdmin.as_view(), name = "admin_eliminar"),

    path("Mis_productos/",views.MisProductos.as_view(), name="Mis_procductos"),
  

]

Inmob_Venta/apps/productos/models.py
from django.db import models
from apps.usuarios.models import Usuario

class Categorias(models.Model):
	nombre = models.CharField(max_length=250)


	class Meta:
		db_table:"Categorias"

	def __str__(self):
		return self.nombre

class Estado(models.Model):
	nombre = models.CharField(max_length=250)


	class Meta:
		db_table:"Estado"

	def __str__(self):
		return self.nombre

ESTADO_CHOICE= (
	(1, "En Venta"),
	(2, "Reservado"),
	(3,"Vendido"),
	(4, "En Alquiler"),
	(5, "Alquilado")

	)

class Productos(models.Model):
	nombre = models.CharField(max_length=250)
	precio = models.DecimalField(max_digits=10,decimal_places=2)
	detalle = models.TextField( default="")
	

	#Categorias = models.ManyToManyField(Categorias)#RELACION n A n
	Categorias = models.ForeignKey(Categorias,on_delete=models.CASCADE,null=True)#RELACION n A  1 
	
	usuario= models.ForeignKey(Usuario,on_delete=models.CASCADE,null=True)
	#Estado = models.ForeignKey(Estado,on_delete=models.CASCADE,null=True)
	Estado = models.IntegerField(choices=ESTADO_CHOICE,default=1)
	imagen = models.ImageField(upload_to="productos", null=True)

	class Meta:
		db_table:"productos"
	
	def __str__(self):
		return self.nombre
	

Inmob_Venta/apps/productos/forms.py
from django import forms
from . models import Productos

class ProductoForm(forms.ModelForm):
	nombre = forms.CharField(label="Nombre del Producto",widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Ingrese el nombre del producto"}))
	detalle = forms.CharField(widget =forms.Textarea(attrs={"class":"form-control"}))
	class Meta:
		model = Productos
		fields = ["nombre","precio","detalle","Categorias","Estado","imagen"]

Inmob_Venta/apps/productos/views.py
from django.contrib.auth.mixins		import LoginRequiredMixin #para que se authentique el usuario
from django.shortcuts 				import render
from django.urls 					import reverse_lazy
from django.views.generic 			import ListView, CreateView
from django.views.generic.edit 		import UpdateView, DeleteView
from django.views.generic.detail 	import DetailView
from apps.core.mixins 				import AdminRequiredMixins


from .models 				import Productos
from .forms 				import ProductoForm

"""
def detalle (request):
	context = {}
	return render(request, "productos/detalle.html", context )
"""

class ListarAdmin (LoginRequiredMixin,AdminRequiredMixins,ListView):
	template_name= "productos/admin/listar.html"
	model = Productos
	context_object_name= "productos"
	paginate_by=3


	def get_context_data(self, ** kwargs):
		context = super (ListarAdmin, self).get_context_data(** kwargs)
		context ["nombre_buscado"] = self.request.GET.get("nombre_producto","")
		return context

	def get_queryset(self):
		busqueda_nombre = self.request.GET.get("nombre_producto","")
		query = Productos.objects.all().order_by("nombre")
		if len(busqueda_nombre) > 0:
			query = query.filter(nombre__icontains=busqueda_nombre)
		return query 

class MisProductos (LoginRequiredMixin,AdminRequiredMixins,ListView):
	template_name= "productos/admin/listar.html"
	model = Productos
	context_object_name= "productos"
	paginate_by=1


	def get_queryset(self):
		return Productos.objects.filter(usuario_id=self.request.user.id)
	

class NuevoAdmin(LoginRequiredMixin,AdminRequiredMixins,CreateView):
	template_name= "productos/admin/nuevo.html"
	model = Productos
	form_class = ProductoForm


	def get_success_url(self, **kwargs):
		return reverse_lazy("productos:admin_listar")

	def form_valid(self, form):
		f=form.save(commit=False)
		f.usuario_id = self.request.user.id
		return super(NuevoAdmin, self).form_valid(form)

class EditarAdmin(LoginRequiredMixin,AdminRequiredMixins,UpdateView):
	template_name= "productos/admin/editar.html"
	model = Productos
	form_class = ProductoForm

	def get_success_url(self, **kwargs):
		return reverse_lazy("productos:admin_listar")

class EliminarAdmin(LoginRequiredMixin,AdminRequiredMixins,DeleteView):
	template_name= "productos/admin/eliminar.html"
	model = Productos
	form_class = ProductoForm

	def get_success_url(self, **kwargs):
		return reverse_lazy("productos:admin_listar")


class Detalle(DetailView):
	template_name= "productos/detalle.html"
	model = Productos

class Listar(ListView):
	template_name= "productos/lista.html"
	model = Productos
	context_object_name= "productos"
	paginate_by=3


	def get_context_data(self, ** kwargs):
		context = super (Listar, self).get_context_data(** kwargs)
		context ["nombre_buscado"] = self.request.GET.get("nombre_producto","")
		return context

	def get_queryset(self):
		busqueda_nombre = self.request.GET.get("nombre_producto","")
		query = Productos.objects.all().order_by("nombre")
		if len(busqueda_nombre) > 0:
			query = query.filter(nombre__icontains=busqueda_nombre)
		return query 

Inmob_Venta/templates/productos/admin/editar.html
{% extends "base/base.html" %}

	{% block portada %}
		<section class="py-5 text-center container">
		    <div class="row py-lg-5">
		      <div class="col-lg-6 col-md-8 mx-auto">
		      	{% include "include/alert.html" %}
		      	<div class="alert alert-primary d-flex align-items-center" role="alert">
				  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:"><use xlink:href="#info-fill"/></svg>
				  <div>
					   <h1 class="py-1 text-center container">Esta ediatando</h1>
			        	<h1 class="py-1 text-center container">{{productos.nombre}}  </h1>
				  </div>
				</div>
		      </div>
		    </div>
		</section>
	{% endblock portada %}

{% block contenido %}

	<form method="POST" enctype="multipart/form-data">{% csrf_token %}
		{% include "include/form_errors.html" %}

		{{form.as_p}}
	
		
		<div class="row" style="padding:10px;">
			<div class="col">
				<button type='submit' class="btn btn-outline-success">Guardar</button>
				<a class="btn btn-outline-danger" href="{% url 'productos:admin_listar' %}" >Cancelar</a>
			</div>
		</div>
	</form>
{% endblock contenido %}

Inmob_Venta/templates/productos/admin/eliminar.html
{% extends "base/base.html" %}
	{% block Menu %}
		
	{% endblock Menu %}
	{% block portada %}
		<section class="py-5 text-center container">
		    <div class="row py-lg-5">
		      <div class="col-lg-6 col-md-8 mx-auto">
		      	{% include "include/alert.html" %}
		      	<div class="alert alert-danger d-flex align-items-center" role="alert">
					  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/>
					  </svg>  
				  <div>
				    <h1 >Ustede esta por eliminar </h1>
		        	<h1  >{{productos.nombre}}  </h1>
				  </div>
				</div>
		       
		      </div>
		    </div>
		</section>
	{% endblock portada %}
{% block contenido %}

	

	<form method="POST" enctype="multipart/form-data">{% csrf_token %}
		{% include "include/form_errors.html" %}


		{{form.as_p}}
	
		<table class="table table-success table-striped">
		  <thead>
		    <tr>
		    <th scope="col">Id</th>
		      <th scope="col">Nombre</th>
		      <th scope="col">Precio</th>
		      <th scope="col">Detalle</th>
		      <th scope="col">Estado</th>
		      <th scope="col">Categorias</th>
		    </tr>
		  </thead>
		  <tbody>

		    	<tr>
			      <th scope="row">{{productos.id}}</th>
			      <td>{{productos.nombre}}</td>
			      <td>$ {{productos.precio}}</td>
			      <td>{{productos.detalle}}</td>
			      <td>{{productos.Estado.nombre}}</td>
			      <td>{{productos.Categorias.nombre}}</td>
			    </tr>
		  </tbody>
		</table>
		<div class="row" style="padding:10px;">
			<div class="col">
				<button type='submit' class="btn btn-outline-danger">Eliminar</button>
				<a class="btn btn-outline-primary" href="{% url 'productos:admin_listar' %}" >Cancelar</a>
			</div>
		</div>
	</form>
{% endblock contenido %}

Inmob_Venta/templates/productos/admin/listar.html
{% extends "base/base.html" %}	
		{% if user.es_administrador %}
				<div class="row" style="padding:20px;">	
					<div class="col">
						<a href="{% url 'productos:admin_nuevo' %}" class="btn btn-outline-success">Nuevo</a>
					</div>
				</div>
	
 		{% endif %}

	{% block Menu %}
		
	{% endblock Menu %}
	{% block footer %}
			
	{% endblock footer %}
		
	{% block portada %}
		<section class="py-5 text-center container">
		    <div class="row py-lg-5">
		      <div class="col-lg-6 col-md-8 mx-auto">
		        <h1 class="fw-light">Listado de propiedades </h1>
		      </div>
		    </div>
		</section>
	{% endblock portada %}
{% block contenido %}
	
	<form class="form-inline my-2 my-lg-0" style="padding:50px;" method="GET">
	 	<div class="row">
	 		<div class="col-md-10">
	 			<input class="form-control mr-sm-2" name = "nombre_producto" type="search" placeholder="Ingrese el nombre de la propiedad...." aria-label="search" value="{{nombre_buscado}}">
	 		</div>
	 		<div class="col-md-2">
				<button class="btn btn-outline-dark" type="submit">Buscar</button>
			</div>
		</div>

    </form>
    {% include "base/menu.html" %}

		<div class="row" style="padding:20px;">	
			<div class="col">
				<a href="{% url 'productos:admin_nuevo' %}" class="btn btn-outline-success">Nuevo</a>
			</div>
		</div>

		

    
	<table class="table table-success table-striped">
		  <thead>
		    <tr>
		      <th scope="col">Id</th>
		      <th scope="col">Nombre</th>
		      <th scope="col">Precio</th>
		      <th scope="col">Detalle</th>
		      <th scope="col">Estado</th>
		      <th scope="col">Categorias</th>
		      <th scope="col">Acciones</th>
		    </tr>
		  </thead>
		  <tbody>
		  	
		    {% for p in productos  %}
		    	<tr>
				      <th scope="row">{{p.id}}</th>
				      <td>{{p.nombre}}</td>
				      <td>$ {{p.precio}}</td>
				      <td>{{p.detalle}}</td>
				      <td>{{p.Estado.nombre}}</td>
				      <td>{{p.Categorias.nombre}}</td>
			      	<!--
			      	{% for c in p.Categorias.all  %}
						<td>{{c.nombre}}</td>
					{% endfor %}
					-->
					<td>
				      	<a href="{% url 'productos:detalle' p.id %}">Ver</a>
				      	<a href="{% url 'productos:admin_editar' p.id %}"class="link-success">Editar</a>
				      	<a href="{% url 'productos:admin_eliminar' p.id %}"class="link-danger">Eliminar</a>
				    </td>
			   	</tr> 
		    {% endfor %}
		  </tbody>
	</table>
	{% include "include/paginador.html" %}
{% endblock contenido %}
	

Inmob_Venta/templates/productos/admin/nuevo.html
{% extends "base/base.html" %}

{% block contenido %}

	
	<form method="POST" enctype="multipart/form-data">{% csrf_token %}
		{% include "include/form_errors.html" %}
		
		{{form.as_p}}
		
		<div class="row" style="padding:10px;">
			<div class="col">
				<button type='submit' class="btn btn-outline-success">Guardar</button>
				<a href="{% url 'productos:admin_listar' %}" class="btn btn-outline-danger">Cancelar</a>
			</div>
		</div>
	</form>
{% endblock contenido %}